# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lm_coef_cpp <- function(X, y) {
    .Call('_easyLM_lm_coef_cpp', PACKAGE = 'easyLM', X, y)
}

